import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  ArrowLeft, 
  Send, 
  ThumbsUp, 
  Sparkles, 
  BookOpen,
  ChevronDown 
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useNavigate } from "react-router-dom";
import { useToast } from "@/hooks/use-toast";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface Question {
  id: number;
  title: string;
  subject: string;
  upvotes: number;
  aiAnswer?: string;
  showAnswer: boolean;
}

const HelpDesk = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [questions, setQuestions] = useState<Question[]>([
    {
      id: 1,
      title: "How do I solve quadratic equations using the quadratic formula?",
      subject: "Mathematics",
      upvotes: 12,
      showAnswer: false,
    },
    {
      id: 2,
      title: "What's the difference between DNA and RNA?",
      subject: "Biology",
      upvotes: 8,
      showAnswer: false,
    },
    {
      id: 3,
      title: "Can someone explain the American Revolution causes?",
      subject: "History",
      upvotes: 15,
      showAnswer: false,
    },
  ]);
  const [isGeneratingAI, setIsGeneratingAI] = useState<number | null>(null);

  const handleUpvote = (id: number) => {
    setQuestions(questions.map(q => 
      q.id === id ? { ...q, upvotes: q.upvotes + 1 } : q
    ));
    toast({
      title: "Upvoted! 👍",
      description: "+5 XP earned for helpful interaction",
    });
  };

  const handleAIAnswer = async (id: number) => {
    setIsGeneratingAI(id);
    await new Promise((resolve) => setTimeout(resolve, 2000));
    
    setQuestions(questions.map(q => 
      q.id === id ? {
        ...q,
        aiAnswer: "Here's a comprehensive answer generated by AI: The topic involves understanding key concepts and applying them step-by-step. Let me break this down for you with detailed explanations and examples that will help you master this concept...",
        showAnswer: true,
      } : q
    ));
    
    setIsGeneratingAI(null);
    toast({
      title: "AI Answer Generated! ✨",
      description: "Answer powered by Gemini AI",
    });
  };

  const toggleAnswer = (id: number) => {
    setQuestions(questions.map(q => 
      q.id === id ? { ...q, showAnswer: !q.showAnswer } : q
    ));
  };

  return (
    <div className="min-h-screen bg-background p-4">
      <div className="container mx-auto max-w-6xl">
        <Button
          variant="ghost"
          onClick={() => navigate("/dashboard")}
          className="mb-6 text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Dashboard
        </Button>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <div className="inline-block gradient-bg p-4 rounded-2xl mb-4">
            <BookOpen className="w-12 h-12 text-white" />
          </div>
          <h1 className="text-5xl font-bold gradient-text mb-4">HelpDesk</h1>
          <p className="text-xl text-muted-foreground">
            Get AI & peer homework answers instantly
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Post Question Form */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="glass-card p-8 h-fit space-y-6"
          >
            <h2 className="text-2xl font-bold gradient-text flex items-center gap-2">
              <Sparkles className="w-6 h-6" />
              Ask a Question
            </h2>

            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="subject" className="text-base">
                  Subject
                </Label>
                <Select>
                  <SelectTrigger id="subject" className="glass-card">
                    <SelectValue placeholder="Select subject" />
                  </SelectTrigger>
                  <SelectContent className="glass-card">
                    <SelectItem value="math">Mathematics</SelectItem>
                    <SelectItem value="science">Science</SelectItem>
                    <SelectItem value="english">English</SelectItem>
                    <SelectItem value="history">History</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="title" className="text-base">
                  Question Title
                </Label>
                <Input
                  id="title"
                  placeholder="Brief summary of your question"
                  className="glass-card"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="details" className="text-base">
                  Question Details
                </Label>
                <Textarea
                  id="details"
                  placeholder="Provide more context and details..."
                  rows={6}
                  className="glass-card resize-none"
                />
              </div>

              <Button className="w-full gradient-bg text-white font-bold py-6 text-lg hover:scale-105 transition-transform">
                <Send className="w-5 h-5 mr-2" />
                Post Question
              </Button>
            </div>
          </motion.div>

          {/* Questions List */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="space-y-4"
          >
            <h2 className="text-2xl font-bold mb-6">Recent Questions</h2>
            
            {questions.map((question, index) => (
              <motion.div
                key={question.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="glass-card p-6 space-y-4"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="px-3 py-1 rounded-full text-xs font-medium bg-primary/20 text-primary">
                        {question.subject}
                      </span>
                    </div>
                    <h3 className="text-lg font-semibold mb-2">{question.title}</h3>
                  </div>

                  <motion.button
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                    onClick={() => handleUpvote(question.id)}
                    className="flex flex-col items-center gap-1 glass-card px-3 py-2 rounded-xl"
                  >
                    <ThumbsUp className="w-5 h-5 text-neon-green" />
                    <span className="text-sm font-bold">{question.upvotes}</span>
                  </motion.button>
                </div>

                <div className="flex gap-3">
                  <Button
                    onClick={() => handleAIAnswer(question.id)}
                    disabled={isGeneratingAI === question.id}
                    className="flex-1 gradient-bg text-white font-medium hover:scale-105 transition-transform"
                  >
                    {isGeneratingAI === question.id ? (
                      "Generating..."
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 mr-2" />
                        AI Answer
                      </>
                    )}
                  </Button>

                  {question.aiAnswer && (
                    <Button
                      onClick={() => toggleAnswer(question.id)}
                      variant="outline"
                      className="glass-card"
                    >
                      <ChevronDown className={`w-5 h-5 transition-transform ${question.showAnswer ? 'rotate-180' : ''}`} />
                    </Button>
                  )}
                </div>

                {/* AI Answer */}
                <AnimatePresence>
                  {question.aiAnswer && question.showAnswer && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      exit={{ opacity: 0, height: 0 }}
                      className="glass-card p-4 border-l-4 border-neon-green"
                    >
                      <div className="flex items-center gap-2 mb-3">
                        <Sparkles className="w-4 h-4 text-neon-green" />
                        <span className="text-sm font-bold text-neon-green">AI-Generated Answer</span>
                      </div>
                      <p className="text-muted-foreground leading-relaxed">
                        {question.aiAnswer}
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default HelpDesk;
